/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddItemsToCartRequest
 */
@JsonPropertyOrder({
  AddItemsToCartRequest.JSON_PROPERTY_PRODUCT_ID,
  AddItemsToCartRequest.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("addItemsToCart_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-14T11:50:35.267105-07:00[America/Los_Angeles]", comments = "Generator version: 7.20.0")
public class AddItemsToCartRequest {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @javax.annotation.Nonnull
  private Integer productId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  @javax.annotation.Nonnull
  private Integer quantity;

  public AddItemsToCartRequest() {
  }

  public AddItemsToCartRequest productId(@javax.annotation.Nonnull Integer productId) {
    
    this.productId = productId;
    return this;
  }

  /**
   * Unique identifier for the product
   * minimum: 1
   * @return productId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(@javax.annotation.Nonnull Integer productId) {
    this.productId = productId;
  }

  public AddItemsToCartRequest quantity(@javax.annotation.Nonnull Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Number of items to add
   * minimum: 1
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(value = JSON_PROPERTY_QUANTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(@javax.annotation.Nonnull Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddItemsToCartRequest addItemsToCartRequest = (AddItemsToCartRequest) o;
    return Objects.equals(this.productId, addItemsToCartRequest.productId) &&
        Objects.equals(this.quantity, addItemsToCartRequest.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddItemsToCartRequest {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

