/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateProduct201Response
 */
@JsonPropertyOrder({
  CreateProduct201Response.JSON_PROPERTY_PRODUCT_ID
})
@JsonTypeName("createProduct_201_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-14T11:50:35.267105-07:00[America/Los_Angeles]", comments = "Generator version: 7.20.0")
public class CreateProduct201Response {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  @javax.annotation.Nullable
  private Integer productId;

  public CreateProduct201Response() {
  }

  public CreateProduct201Response productId(@javax.annotation.Nullable Integer productId) {
    
    this.productId = productId;
    return this;
  }

  /**
   * Unique identifier for the created product
   * @return productId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProductId() {
    return productId;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProduct201Response createProduct201Response = (CreateProduct201Response) o;
    return Objects.equals(this.productId, createProduct201Response.productId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProduct201Response {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

