/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateShoppingCart201Response
 */
@JsonPropertyOrder({
  CreateShoppingCart201Response.JSON_PROPERTY_SHOPPING_CART_ID
})
@JsonTypeName("createShoppingCart_201_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-14T11:50:35.267105-07:00[America/Los_Angeles]", comments = "Generator version: 7.20.0")
public class CreateShoppingCart201Response {
  public static final String JSON_PROPERTY_SHOPPING_CART_ID = "shopping_cart_id";
  @javax.annotation.Nullable
  private Integer shoppingCartId;

  public CreateShoppingCart201Response() {
  }

  public CreateShoppingCart201Response shoppingCartId(@javax.annotation.Nullable Integer shoppingCartId) {
    
    this.shoppingCartId = shoppingCartId;
    return this;
  }

  /**
   * Unique identifier for the created shopping cart
   * @return shoppingCartId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOPPING_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getShoppingCartId() {
    return shoppingCartId;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOPPING_CART_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShoppingCartId(@javax.annotation.Nullable Integer shoppingCartId) {
    this.shoppingCartId = shoppingCartId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateShoppingCart201Response createShoppingCart201Response = (CreateShoppingCart201Response) o;
    return Objects.equals(this.shoppingCartId, createShoppingCart201Response.shoppingCartId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shoppingCartId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateShoppingCart201Response {\n");
    sb.append("    shoppingCartId: ").append(toIndentedString(shoppingCartId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

