/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProcessPaymentRequest
 */
@JsonPropertyOrder({
  ProcessPaymentRequest.JSON_PROPERTY_CREDIT_CARD_NUMBER
})
@JsonTypeName("processPayment_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-14T11:50:35.267105-07:00[America/Los_Angeles]", comments = "Generator version: 7.20.0")
public class ProcessPaymentRequest {
  public static final String JSON_PROPERTY_CREDIT_CARD_NUMBER = "credit_card_number";
  @javax.annotation.Nonnull
  private String creditCardNumber;

  public ProcessPaymentRequest() {
  }

  public ProcessPaymentRequest creditCardNumber(@javax.annotation.Nonnull String creditCardNumber) {
    
    this.creditCardNumber = creditCardNumber;
    return this;
  }

  /**
   * Credit card number as string as groups of 4 digits with dashes (minus sign)
   * @return creditCardNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreditCardNumber() {
    return creditCardNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditCardNumber(@javax.annotation.Nonnull String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessPaymentRequest processPaymentRequest = (ProcessPaymentRequest) o;
    return Objects.equals(this.creditCardNumber, processPaymentRequest.creditCardNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCardNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessPaymentRequest {\n");
    sb.append("    creditCardNumber: ").append(toIndentedString(creditCardNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

