/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ProcessPaymentRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * Authorize and process credit card payment, called by shoppinCart.checkout. Internal API
     *
     * Process payment for a shopping cart using credit card information
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void processPaymentTest() {
        ProcessPaymentRequest processPaymentRequest = null;

        api.processPayment(processPaymentRequest);

        // TODO: test validations
    }
    
}
