/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.CreateProduct201Response;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Product;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductApi
 */
@Disabled
class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * Create a product, with the provided details
     *
     * Create a product, with the provided details. Server creates the new product_id.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void createProductTest() {
        Product product = null;

        CreateProduct201Response response = api.createProduct(product);

        // TODO: test validations
    }
    
    /**
     * Get product by ID
     *
     * Retrieve a product&#39;s details using its unique identifier
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getProductTest() {
        Integer productId = null;

        Product response = api.getProduct(productId);

        // TODO: test validations
    }
    
}
