/*
 * E-commerce API
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.AddItemsToCartRequest;
import org.openapitools.client.model.CheckoutCart200Response;
import org.openapitools.client.model.CheckoutCartRequest;
import org.openapitools.client.model.CreateShoppingCart201Response;
import org.openapitools.client.model.CreateShoppingCartRequest;
import org.openapitools.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShoppingCartApi
 */
@Disabled
class ShoppingCartApiTest {

    private final ShoppingCartApi api = new ShoppingCartApi();

    
    /**
     * Add items to shopping cart
     *
     * Add products with specified quantities to a shopping cart
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void addItemsToCartTest() {
        Integer shoppingCartId = null;
        AddItemsToCartRequest addItemsToCartRequest = null;

        api.addItemsToCart(shoppingCartId, addItemsToCartRequest);

        // TODO: test validations
    }
    
    /**
     * Checkout shopping cart
     *
     * Process checkout for a shopping cart
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void checkoutCartTest() {
        Integer shoppingCartId = null;
        CheckoutCartRequest checkoutCartRequest = null;

        CheckoutCart200Response response = api.checkoutCart(shoppingCartId, checkoutCartRequest);

        // TODO: test validations
    }
    
    /**
     * Create a new shopping cart
     *
     * Create a new shopping cart for a customer
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void createShoppingCartTest() {
        CreateShoppingCartRequest createShoppingCartRequest = null;

        CreateShoppingCart201Response response = api.createShoppingCart(createShoppingCartRequest);

        // TODO: test validations
    }
    
}
