/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.AddItemsToCartRequest;
import org.openapitools.model.CheckoutCart200Response;
import org.openapitools.model.CheckoutCartRequest;
import org.openapitools.model.CreateShoppingCart201Response;
import org.openapitools.model.CreateShoppingCartRequest;
import org.openapitools.model.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-14T11:50:51.562192-07:00[America/Los_Angeles]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Shopping Cart", description = "Shopping cart operations")
public interface ShoppingCartApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ADD_ITEMS_TO_CART = "/shopping-carts/{shoppingCartId}/addItem";
    /**
     * POST /shopping-carts/{shoppingCartId}/addItem : Add items to shopping cart
     * Add products with specified quantities to a shopping cart
     *
     * @param shoppingCartId Unique identifier for the shopping cart (required)
     * @param addItemsToCartRequest  (required)
     * @return Items added to cart successfully (status code 204)
     *         or Invalid input data (status code 400)
     *         or Shopping cart or product not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "addItemsToCart",
        summary = "Add items to shopping cart",
        description = "Add products with specified quantities to a shopping cart",
        tags = { "Shopping Cart" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Items added to cart successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid input data", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Shopping cart or product not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ShoppingCartApi.PATH_ADD_ITEMS_TO_CART,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> addItemsToCart(
        @NotNull @Min(value = 1) @Parameter(name = "shoppingCartId", description = "Unique identifier for the shopping cart", required = true, in = ParameterIn.PATH) @PathVariable("shoppingCartId") Integer shoppingCartId,
        @Parameter(name = "AddItemsToCartRequest", description = "", required = true) @Valid @RequestBody AddItemsToCartRequest addItemsToCartRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CHECKOUT_CART = "/shopping-carts/{shoppingCartId}/checkout";
    /**
     * POST /shopping-carts/{shoppingCartId}/checkout : Checkout shopping cart
     * Process checkout for a shopping cart
     *
     * @param shoppingCartId Unique identifier for the shopping cart (required)
     * @param checkoutCartRequest  (required)
     * @return Checkout processed successfully (status code 200)
     *         or Invalid shopping cart state (status code 400)
     *         or Shopping cart not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "checkoutCart",
        summary = "Checkout shopping cart",
        description = "Process checkout for a shopping cart",
        tags = { "Shopping Cart" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Checkout processed successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CheckoutCart200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid shopping cart state", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Shopping cart not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ShoppingCartApi.PATH_CHECKOUT_CART,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CheckoutCart200Response> checkoutCart(
        @NotNull @Min(value = 1) @Parameter(name = "shoppingCartId", description = "Unique identifier for the shopping cart", required = true, in = ParameterIn.PATH) @PathVariable("shoppingCartId") Integer shoppingCartId,
        @Parameter(name = "CheckoutCartRequest", description = "", required = true) @Valid @RequestBody CheckoutCartRequest checkoutCartRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"order_id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_SHOPPING_CART = "/shopping-cart";
    /**
     * POST /shopping-cart : Create a new shopping cart
     * Create a new shopping cart for a customer
     *
     * @param createShoppingCartRequest  (required)
     * @return Shopping cart created successfully (status code 201)
     *         or Invalid input data (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createShoppingCart",
        summary = "Create a new shopping cart",
        description = "Create a new shopping cart for a customer",
        tags = { "Shopping Cart" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Shopping cart created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateShoppingCart201Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input data", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth"),
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ShoppingCartApi.PATH_CREATE_SHOPPING_CART,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreateShoppingCart201Response> createShoppingCart(
        @Parameter(name = "CreateShoppingCartRequest", description = "", required = true) @Valid @RequestBody CreateShoppingCartRequest createShoppingCartRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"shopping_cart_id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"details\" : \"Product ID must be a positive integer\", \"error\" : \"INVALID_INPUT\", \"message\" : \"The provided input data is invalid\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
